if (WIN32 AND NOT UNIX)

    INSTALL(TARGETS  ${CMAKE_PROJECT_NAME} 
        RUNTIME DESTINATION /
        PERMISSIONS OWNER_EXECUTE
    )

    if (CMAKE_BUILD_TYPE STREQUAL Release)

        INSTALL(FILES ${CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE}/libusb-1.0.dll
            DESTINATION /
            CONFIGURATIONS Release
            # COMPONENT Runtime
        )

    elseif(CMAKE_BUILD_TYPE STREQUAL Debug)

        INSTALL(FILES ${CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG}/libusb-1.0.dll
            DESTINATION /
            CONFIGURATIONS Debug
            # COMPONENT Runtime
        )

    endif()

    INSTALL(FILES LICENSE README.MD DESTINATION /)

else (WIN32)

    INSTALL(TARGETS  ${CMAKE_PROJECT_NAME} 
        RUNTIME DESTINATION bin
        COMPONENT Runtime
    )

endif(WIN32)
